# Generated by Django 5.1.1 on 2024-10-28 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0003_facultad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carrera', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/carreras/')),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('modalidad_inscripcion', models.CharField(choices=[('anual', 'Anual'), ('semestral', 'Semestral')], max_length=10)),
                ('costo_matricula', models.DecimalField(decimal_places=2, max_digits=10)),
                ('facultad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geodata.facultad')),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geodata.universidad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
