# Generated by Django 5.1.1 on 2024-12-10 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0008_favorita'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Point',
        ),
    ]
